### ISSUE TITLE
'Unable to find zbar shared library

### ISSUE THREAD

**Issue by why2lyj** [why2lyj/youxiang-Itchat#11]
ubuntu16.04安装方式 
```shell
sudo apt-get install libzbar-dev
pip install zbar
```
centos7 安装方式
```shell
yum install python-devel
yum install zbar-devel
pip install zbar
```

![微信图片_20211117154236](https://user-images.githubusercontent.com/31466760/142157141-e3774bb3-8ceb-4021-a215-990b0a36573f.png)

**Comment by danalex7212** [comment]
How did you solve this ?
