### ISSUE TITLE
文件可以登录，微信登录不了

### ISSUE THREAD

**Issue by Yuri2** [why2lyj/youxiang-Itchat#12]
wx.qq.com微信登录不了

<error><ret>1203</ret><message>由于安全原因，此微信号不能使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。</message></error>

**Comment by Yuri2** [comment]
两个方法都不行

**Comment by why2lyj** [comment]
嗯，截至到目前两个方法都无法绕过登陆限制。
